README.md
java.jdbc-ballerina/src/java.jdbc/tests/execute/execute-basic-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/execute/execute-params-query-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/query/complex-query-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/query/numerical-query-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/query/simple-params-query-test.bal

Enable Datetime test cases

---

README.md
java.jdbc-ballerina/src/java.jdbc/client.bal

Migrating change as per ballerina-lang update in https://github.com/ballerina-platform/ballerina-lang/pull/25228

Remove public keyword in function params

---

java.jdbc-ballerina/build.gradle
java.jdbc-ballerina/src/java.jdbc/client.bal

Add Ballerina class support

---

java.jdbc-ballerina/build.gradle
java.jdbc-ballerina/src/java.jdbc/tests/pool/connection-pool-test.bal

Remove lang imports

---

java.jdbc-native/src/main/java/org/ballerinalang/jdbc/Constants.java
java.jdbc-native/src/main/java/org/ballerinalang/jdbc/NativeImpl.java

Migrate jBallerina Runtime APIs

---

.github/workflows/pull-request.yml

Enable build from forks

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/build.gradle

Improve release work flow

---

.gitignore

Update gitignore file with ballerina lock file

---

java.jdbc-ballerina/src/java.jdbc/Module.md

Fix the JDBC Driver path.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Fix the JDBC Driver Path

---

java.jdbc-native/src/main/java/module-info.java
java.jdbc-native/src/main/java/org/ballerinalang/jdbc/Constants.java
java.jdbc-native/src/main/java/org/ballerinalang/jdbc/NativeImpl.java

Refactor ballerina runtime api usages
Dependant on https://github.com/ballerina-platform/ballerina-lang/pull/26278

Migrate ballerina runtime apis

---

README.md
java.jdbc-ballerina/build.gradle

Enable code coverage generation

---

README.md

Update README with latest issues link

---

java.jdbc-ballerina/src/java.jdbc/Module.md

Fix the SQL module link.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Fix the SQL module link

---

.github/workflows/pull-request.yml
README.md
java.jdbc-ballerina/src/java.jdbc/tests/query/query-taint-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/resources/sql/query/query-taint-analysis-data.sql

> Refactor and move testcases from ballerina-lang repo.

Add query taint test cases

---

java.jdbc-ballerina/src/java.jdbc/tests/pool/connection-pool-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/transaction/local-transaction-test.bal
java.jdbc-ballerina/src/java.jdbc/tests/transaction/xa-transactions-test.bal

These reverts commit e342b78b as the original issue is fixed by https://github.com/ballerina-platform/ballerina-lang/pull/26999

Revert "Disable transaction test cases temporarily"

---

java.jdbc-ballerina/tests/local-transaction-test.bal

Enable transaction testcase

---

gradle.properties

Bump Transactions internal module version

---

gradle.properties
java.jdbc-ballerina/client.bal
java.jdbc-ballerina/tests/local-transaction-test.bal
java.jdbc-ballerina/tests/xa-transactions-test.bal

Migrate service type changes

---

java.jdbc-ballerina/Package.md
java.jdbc-ballerina/tests/local-transaction-test.bal

$subject as issue https://github.com/ballerina-platform/ballerina-lang/issues/27381 is fixed

Reenable test assertions for transactions

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
java.jdbc-ballerina/tests/local-transaction-test.bal

$subject design discussion raised in https://github.com/ballerina-platform/ballerina-standard-library/issues/727

Temporarily fix transaction retry test cases

---

java.jdbc-ballerina/Package.md

Fix toml structure in doc

---

build.gradle
gradle.properties
java.jdbc-ballerina/tests/batch-execute-query-test.bal
java.jdbc-ballerina/tests/execute-basic-test.bal
java.jdbc-ballerina/tests/execute-params-query-test.bal
java.jdbc-ballerina/tests/local-transaction-test.bal

Migrate testerina api changes

---

build.gradle
gradle.properties
java.jdbc-ballerina/tests/complex-query-test.bal
java.jdbc-ballerina/tests/connection-pool-test.bal

Migrate to regex module

---

java.jdbc-ballerina/tests/local-transaction-test.bal

> Update tests to sync with marking commit and rollback handler types as isolated
> Link to the PR for changes to the training …

Update tests to sync with trx handlers as isolated

---

java.jdbc-ballerina/build.gradle

Update ballerina command to bal
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

Update ballerina command to bal command

---

java.jdbc-ballerina/tests/local-transaction-test.bal

> Use isolated variable to assert transaction handler execution
> Link to the PR for changes to the training content in …

Use isolated var to assert trx handler execution

---

java.jdbc-ballerina/client.bal

Related Issue: ballerina-platform/ballerina-lang#28034
> Link to the PR for changes to the training content in …

Change the name of the `java` langlib module to `jballerina.java`

---

java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/Package.md
java.jdbc-ballerina/build.gradle

Change org and module name

---

java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/Dependencies.toml
java.jdbc-ballerina/build.gradle

Fixes ballerina-platform/ballerina-lang#27988

Add Dependencies.toml

---

java.jdbc-ballerina/build.gradle

Improve build task to revert depedendency toml

---

gradle.properties

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

[Automated] Update lang version to 2.0.0-alpha-SNAPSHOT

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
README.md
build-config/spotbugs-exclude.xml
build.gradle
gradle.properties
java.jdbc-ballerina/build.gradle
java.jdbc-native/build.gradle

> This is to Enable code coverage, check styles, and spot bugs

Enable code coverage, check styles, and spot bugs

---

java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/build.gradle

> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476

Change ballerina archive extension to bala

---

README.md
java.jdbc-ballerina/Package.md

>This is to change the BBE URL links consists of  /swan-lake/learn to /learn

Change the URL links consists of /swan-lake/learn

---

.github/workflows/publish-release.yml
README.md
build.gradle
gradle.properties
java.jdbc-ballerina/build.gradle

> change string module -> package in README.md file.

Change in README.md

---

build.gradle
java.jdbc-ballerina/build.gradle

Re-order build tasks to publish to ballerina central

---

.github/workflows/publish-release.yml
README.md
java.jdbc-ballerina/build.gradle
settings.gradle

Update build scripts for repository name change

---

java.jdbc-ballerina/tests/complex-query-test.bal
java.jdbc-ballerina/tests/connection-pool-test.bal
java.jdbc-ballerina/tests/local-transaction-test.bal

$subject
This also disables intermittently failing test cases in https://github.com/ballerina-platform/module-ballerinai-transaction/issues/100

Fix for removal of error type from anydata

---

build.gradle
gradle.properties

Remove reflect dependency

---

java.jdbc-ballerina/Config.toml
java.jdbc-ballerina/tests/connector-init-test.bal

> $Subject 
Fixes: [#967](https://github.com/ballerina-platform/ballerina-standard-library/issues/967)
@shafreenAnfar 
> https://github.com/ballerina-platform/module-ballerina-sql/pull/140

Change durations such as timeouts, intervals, etc

---

java.jdbc-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

java.jdbc-ballerina/build.gradle
java.jdbc-ballerina/tests/init-h2-database.bal

> $Subject due to removal of exec function in ballerina/os module
> to  help the test process continuation without os:exec function. 
> https://github.com/ballerina-platform/module-ballerina-os/pull/74
> https://github.com/ballerina-platform/module-ballerinax-mysql/pull/87

Create h2 databases from gradle build process

---

java.jdbc-ballerina/build.gradle

> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032

Add -c flag to build command

---

gradle.properties
java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/build.gradle
java.jdbc-ballerina/tests/complex-query-test.bal
java.jdbc-ballerina/tests/simple-params-query-test.bal

> This PR to change the test cases which use Time module APIs. 
Fixes:[ #1079](https://github.com/ballerina-platform/ballerina-standard-library/issues/1079)
> @niveathika @BuddhiWathsala 
> https://github.com/ballerina-platform/module-ballerina-time/pull/68
> https://github.com/ballerina-platform/module-ballerina-sql/pull/150
> https://github.com/ballerina-platform/ballerina-standard-library/issues/1079

Change Test cases for new Time APIs

---

java.jdbc-ballerina/client.bal

> $Subject
> Provide isolated APIs to db client module users
> https://github.com/ballerina-platform/module-ballerina-sql/pull/151

Change module APIs to isolated

---

java.jdbc-ballerina/Package.md

> $subject
Fixes:[ #1120](https://github.com/ballerina-platform/ballerina-standard-library/issues/1120)
> artafactId corrected to artifactId

Fix Typo in Package.md

---

java.jdbc-ballerina/tests/Config.toml
java.jdbc-ballerina/tests/batch-execute-query-test.bal
java.jdbc-ballerina/tests/complex-query-test.bal
java.jdbc-ballerina/tests/connection-pool-test.bal
java.jdbc-ballerina/tests/connector-init-test.bal
java.jdbc-ballerina/tests/execute-basic-test.bal
java.jdbc-ballerina/tests/execute-params-query-test.bal
java.jdbc-ballerina/tests/init-h2-database.bal
java.jdbc-ballerina/tests/local-transaction-test.bal
java.jdbc-ballerina/tests/numerical-query-test.bal
java.jdbc-ballerina/tests/query-taint-test.bal
java.jdbc-ballerina/tests/simple-params-query-test.bal
java.jdbc-ballerina/tests/utils.bal
java.jdbc-ballerina/tests/xa-transactions-test.bal

> This PR to changes test cases because sql module has changes and those changes effect the java.jdbc module as well
>https://github.com/ballerina-platform/module-ballerina-sql/pull/161

Fix failing Test cases

---

README.md
java.jdbc-ballerina/build.gradle

Add configs to publish to local repository

---

.github/workflows/publish-release.yml
java.jdbc-ballerina/build.gradle

Fix maven publish failing

---

.github/workflows/build-master.yml
.github/workflows/publish-release.yml
README.md
java.jdbc-ballerina/build.gradle

Use separate config for Github package publish

---

build.gradle
java.jdbc-ballerina/build.gradle

Strip stdlib dependency version

---

java.jdbc-ballerina/build.gradle

Stop error message when publishing snapshot

---

README.md
java.jdbc-ballerina/Module.md
java.jdbc-ballerina/Package.md
java.jdbc-ballerina/client.bal

$Title
Fixes: https://github.com/ballerina-platform/ballerina-dev-tools/issues/92

Improve the API docs, module MD, and package MD

---

java.jdbc-ballerina/build.gradle

Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'

Update flag for coverage format

---

changelog.md
gradle.properties
java.jdbc-ballerina/client.bal

Make client classes Isolated

---

gradle.properties

Update ballerina plugin verion

---

changelog.md
gradle.properties
java.jdbc-ballerina/client.bal
java.jdbc-ballerina/tests/numerical-query-test.bal
java.jdbc-ballerina/tests/simple-params-query-test.bal
java.jdbc-native/src/main/java/org/ballerinalang/jdbc/nativeimpl/QueryProcessor.java

$title
Fixes for : 
https://github.com/ballerina-platform/ballerina-standard-library/issues/1445
https://github.com/ballerina-platform/module-ballerina-sql/pull/264

Change Return stream type of the query remote method

---

java.jdbc-ballerina/Module.md

$title
Fix for: https://github.com/ballerina-platform/ballerina-standard-library/issues/1463

Improve API docs

---

java.jdbc-ballerina/Module.md

$Subject
Related issue: [1537](https://github.com/ballerina-platform/ballerina-standard-library/issues/1537)  & [1539](https://github.com/ballerina-platform/ballerina-standard-library/issues/1539)

Fix API doc issues

---

java.jdbc-ballerina/Module.md

Fix minor documentation issue

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
java.jdbc-ballerina/Ballerina.toml
java.jdbc-ballerina/build.gradle

Fix release name

---

ballerina/Ballerina.toml
ballerina/build.gradle
build.gradle
gradle.properties

Add sql native dependency

---

ballerina/client.bal
ballerina/tests/complex-query-test.bal
ballerina/tests/connection-pool-test.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/execute-params-query-test.bal
ballerina/tests/local-transaction-test.bal
ballerina/tests/numerical-query-test.bal
ballerina/tests/simple-params-query-test.bal
ballerina/tests/xa-transactions-test.bal
changelog.md
gradle.properties

$title
Related issue ballerina-platform/ballerina-standard-library#1654

Add completion type as nil in SQL query return stream type

---

ballerina/client.bal
ballerina/tests/complex-query-test.bal
ballerina/tests/simple-params-query-test.bal
changelog.md
gradle.properties
native/src/main/java/io/ballerina/stdlib/java/jdbc/nativeimpl/QueryProcessor.java

$title
Fixes ballerina-platform/ballerina-standard-library#1604

Add support for query row

---

gradle.properties
native/src/main/java/io/ballerina/stdlib/java/jdbc/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/java/jdbc/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/java/jdbc/nativeimpl/QueryProcessor.java

Migrate to latest version of SQL dependency

---

ballerina/Dependencies.toml
gradle.properties

$subject. The changes come from SQL dependency
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1807

Improve error types

---

README.md
ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/client.bal
ballerina/tests/complex-query-test.bal
gradle.properties
native/src/main/java/io/ballerina/stdlib/java/jdbc/nativeimpl/QueryProcessor.java

$subject due to SQL module change https://github.com/ballerina-platform/module-ballerina-sql/pull/376
Fixes:

Remove string usages from queryRow and batchUpdate

---

ballerina/Module.md

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1914
Similar PR: https://github.com/ballerina-platform/module-ballerina-sql/pull/379

Update module.md with queryRow() documentation

---

.github/workflows/build-timestamped-master.yml
ballerina/Ballerina.toml

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2362

Skip master build for .md file changes

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/tests/complex-query-test.bal
ballerina/tests/connection-pool-test.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/execute-params-query-test.bal
ballerina/tests/local-transaction-test.bal
ballerina/tests/numerical-query-test.bal
ballerina/tests/simple-params-query-test.bal
ballerina/tests/xa-transactions-test.bal
examples/facebook/posts/posts.bal
examples/snowflake/setup/setup.bal

Remove unused variables

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/client.bal
ballerina/tests/execute-params-query-test.bal
ballerina/tests/simple-params-query-test.bal
gradle.properties

Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2390
To be merged after: https://github.com/ballerina-platform/module-ballerina-sql/pull/441

Change queryRow() API accept anydata as the return-type instead of any

---

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/java/jdbc/compiler/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/JDBCDiagnosticsCode.java
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/analyzer/RemoteMethodAnalyzer.java

Rename diagnostics code for hints

---

compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/analyzer/InitializerParamAnalyzer.java

Fix plugin failure when connectionPool param is nil

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/build.gradle
build.gradle
examples/build.gradle

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2436

Fix publish not depending on build

---

ballerina/client.bal

Add client return type description

---

ballerina/Ballerina.toml
ballerina/Module.md
gradle.properties

$subject due to detected vulnerability

Update h2 test dependency

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/java/jdbc/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample3/Ballerina.toml
compiler-plugin-tests/src/test/resources/diagnostics/sample3/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/analyzer/InitializerParamAnalyzer.java
gradle.properties

Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2625
Added fixes:
https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/316

Patch release for JDBC 1.2.1

---

docs/spec/spec.md

Improve specification introduction

---

.github/workflows/trigger-load-tests.yml

Update repo name in load test yml

---

docs/spec/spec.md

Improve the introduction in the spec

---

gradle.properties

Update Ballerina lang version  to 2201.0.1

---

.github/workflows/central-publish.yml
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2564

Add workflow to push package to Ballerina Central Environments

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
gradle.properties

Update minor version to 1.4.0

---

ballerina/client.bal

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2931

Fix typo in code snippet

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml
gradle.properties

Update to stable lang version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
gradle.properties

Update SQL version

---

.github/workflows/central-publish.yml

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3136

Improve workflow to publish snapshots

---

ballerina/Ballerina.toml
ballerina/tests/complex-query-test.bal

Fix failing test case

---

README.md
ballerina/Module.md
ballerina/Package.md
changelog.md

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3441

Fix sql command in API docs

---

README.md
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/Package.md
build-config/resources/Ballerina.toml
changelog.md
docs/spec/spec.md
gradle.properties

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463

Bump to update 3 dependencies and update Slack references to Discord

---

.github/workflows/build-timestamped-master.yml

Ignore load tests changes for build

---

README.md
ballerina/Module.md
ballerina/Package.md

Rename remote functions-> remote methods

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
changelog.md
gradle.properties

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3763

Enable Non-Hikari logs

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517

Update versions for type-reference-support

---

.github/workflows/build-with-bal-test-native.yml
README.md

> Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/3853

Update GraalVM check link in README

---

compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/Utils.java
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/analyzer/InitializerParamAnalyzer.java

Improve compiler error check before analysing

---

README.md
ballerina/Module.md
ballerina/Package.md
ballerina/client.bal

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3857

Improve API docs based on Best practices

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/build.gradle
build-config/resources/Ballerina.toml
native-image-configs/build.gradle
native-image-configs/src/main/resources/META-INF/native-image/io.ballerina.stdlib/java.jdbc-native-image-configs/reflect-config.json
native-image-configs/src/main/resources/META-INF/native-image/io.ballerina.stdlib/java.jdbc-native-image-configs/resource-config.json
settings.gradle

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3931

Add build workflow with h2 driver native image configurations 

---

ballerina/Ballerina.toml
gradle.properties

Update to latest stdlib dependencies

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-tests/build.gradle
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/java/jdbc/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample4/Ballerina.toml
compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal
compiler-plugin-tests/src/test/resources/diagnostics/sample4/tests/test.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/analyzer/RemoteMethodAnalyzer.java

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4054

Fix JDBC compiler plugins failure when the diagnostic code is null

---

.github/workflows/process-load-test-result.yml
.github/workflows/pull-request.yml
.github/workflows/trigger-load-tests.yml

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4098

Add workflow calls to load test

---

.github/workflows/trigger-load-tests.yml

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4098

Fix trigger load tests workflow

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
compiler-plugin-tests/build.gradle
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/java/jdbc/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample2/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/java/jdbc/compiler/Utils.java
gradle.properties

$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3119
N/A

Enable compiler plugin code coverage

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update dependency versions for update 5

---

.trivyignore

$subject as there is no version with a fix

Remove expiry from vulnerability

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
ballerina/Module.md
ballerina/Package.md
build-config/checkstyle/build.gradle
build-config/resources/Ballerina.toml
compiler-plugin-tests/build.gradle
examples/facebook/posts/README.md
examples/facebook/user-info/README.md
examples/snowflake/README.md
examples/snowflake/service/Ballerina.toml
examples/snowflake/setup/Ballerina.toml
gradle.properties
gradle/wrapper/gradle-wrapper.properties
load-tests/cache/src/Ballerina.toml
load-tests/cache_with_cleanup_task/src/Ballerina.toml
load-tests/non_cache/src/Ballerina.toml
native-image-configs/build.gradle
native/build.gradle
settings.gradle

Migrate to Java 17

---

.gitattributes
ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml

Fix merge conflicts and add git attribute file. 
Fixes:

Fix gradle build

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
gradle.properties

Update h2 driver version

---

ballerina/Dependencies.toml
gradle.properties

Update H2 driver to the timestamped version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update the versions for u9 release

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/process-load-test-result.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trigger-load-tests.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Package.md
changelog.md
docs/spec/spec.md

Change ballerina-standard-library mention to new repo name

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update the version for the update 10 release

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/daily-build.yml
.github/workflows/process-load-test-result.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trigger-load-tests.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
compiler-plugin-tests/build.gradle
compiler-plugin/build.gradle
gradle.properties
native/build.gradle

Migrate to Java 21

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Upgrade to the next minor version
